### ISSUE TITLE
Using library from F#

### ISSUE THREAD

**Issue by tymokvo** [lillo42/cassowary-csharp#15]
Hello,

I have been experimenting with this library for use in an F# project. But, I'm struggling to get it working. 

From comparing the library to the rust examples, I would expect that I should be able to write something like:

```fsharp
open Cassowary

type Element = { left: Variable; right: Variable }

let element () =
    {
        left = new Variable()
        right = new Variable()
    }

let a = element ()

let solver = new Solver()

solver.AddConstraints((a.left | WeightedRelation.Eq(Strength.Required) | 0.0))
```

to create an element that is required to be left-aligned to some region. However, I think the syntax is incompatible with F# as the `|` character is reserved by the language for the "pipe" operators, e.g. `|>`, `||>`, etc.

So, the snippet above results in: `error FS0010: Unexpected symbol '|' in expression`.

Is it possible to express constraint expressions without the `|` character?

**Comment by lillo42** [comment]
Hey, I've override the [OR operator ](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/boolean-logical-operators#logical-or-operator-) I think you need to use  [OR operator in F#](https://learn.microsoft.com/en-us/dotnet/fsharp/language-reference/symbol-and-operator-reference/bitwise-operators) `|||`

**Comment by tymokvo** [comment]
Hm, unfortunately that doesn't work either as the bitwise or operator definition appears to follow the language-level definition before the operator overload. 
Simply replacing it (even with `open type WeightedRelation`) results in: `error FS0001: The type 'float' does not support the operator '|||'`.

But, I was able to use your tip about which operator it is overloading to work around it by using and F#-style operator definition:

```fsharp
let (|||) (f: float) w = WeightedRelation.(|||) (f, w)

0.0 ||| Eq(Strength.Required)
```

Thanks!
